"use client";

import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000";
type Alignment = { course: string; taught: string[]; required: string[]; missing: string[]; alignment: number; status: string };
export default function InstituteView() {
  const [programs, setPrograms] = useState<string[]>([]); const [course, setCourse] = useState(""); const [data, setData] = useState<Alignment | null>(null); const [error, setError] = useState(""); const [proposal, setProposal] = useState(false);
  useEffect(() => { fetch(`${API}/api/institute/programs`).then((response) => response.json()).then((items: string[]) => { setPrograms(items); setCourse(items[0] ?? ""); }).catch(() => setError("Training programmes could not be loaded.")); }, []);
  useEffect(() => { if (course) fetch(`${API}/api/institute/programs/${encodeURIComponent(course)}`).then((response) => { if (!response.ok) throw new Error(); return response.json(); }).then(setData).catch(() => setError("Curriculum alignment could not be loaded.")); }, [course]);
  return <section className="alignment-view">{error && <div className="error-box">{error}</div>}{!data && !error && <div className="loading-box">Loading curriculum alignment...</div>}<label className="wide-select">Training programme<select value={course} onChange={(event) => { setCourse(event.target.value); setProposal(false); }}>{programs.map((item) => <option key={item}>{item}</option>)}</select></label>{data && <><div className="alignment-summary"><div><strong>{data.alignment}%</strong><span>Industry alignment</span></div><div><strong>{data.status}</strong><span>Course health</span></div><div><strong>{data.missing.length}</strong><span>Skills to add</span></div></div><div className="alignment-grid"><article className="career-panel"><div className="panel-kicker">Current curriculum</div><h2>Skills already taught</h2><div className="tag-list">{data.taught.map((skill) => <span className="tag-good" key={skill}>Keep · {skill}</span>)}</div></article><article className="career-panel"><div className="panel-kicker">Recommended curriculum update</div><h2>Add or strengthen</h2><p>These skills appear in high-demand observed job signals and are not covered by this programme.</p><div className="tag-list">{data.missing.slice(0, 8).map((skill) => <span className="tag-warn" key={skill}>Add · {skill}</span>)}</div><button className="primary-action" onClick={() => setProposal(true)}>Generate curriculum update proposal</button>{proposal && <div className="success-box">Proposal ready: retain {data.taught.slice(0, 3).join(", ")} and add {data.missing.slice(0, 5).join(", ")} based on observed demand.</div>}</article></div></>}</section>;
}
